/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedActasIndexRouteImport } from './routes/_authenticated/actas/index'
import { Route as AuthenticatedActasActaIdRouteImport } from './routes/_authenticated/actas/$actaId'
import { Route as AuthenticatedAreasIndexRouteImport } from './routes/_authenticated/areas/index'
import { Route as AuthenticatedPermissionsIndexRouteImport } from './routes/_authenticated/permissions/index'
import { Route as AuthenticatedSistemasIndexRouteImport } from './routes/_authenticated/sistemas/index'
import { Route as AuthenticatedSistemasSistemaIdRouteImport } from './routes/_authenticated/sistemas/$sistemaId'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated/tickets/index'
import { Route as AuthenticatedTicketsTicketIdRouteImport } from './routes/_authenticated/tickets/$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActasIndexRoute = AuthenticatedActasIndexRouteImport.update({
  id: '/actas/',
  path: '/actas/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActasActaIdRoute =
  AuthenticatedActasActaIdRouteImport.update({
    id: '/actas/$actaId',
    path: '/actas/$actaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAreasIndexRoute = AuthenticatedAreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPermissionsIndexRoute =
  AuthenticatedPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSistemasIndexRoute =
  AuthenticatedSistemasIndexRouteImport.update({
    id: '/sistemas/',
    path: '/sistemas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSistemasSistemaIdRoute =
  AuthenticatedSistemasSistemaIdRouteImport.update({
    id: '/sistemas/$sistemaId',
    path: '/sistemas/$sistemaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTicketsTicketIdRoute =
  AuthenticatedTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRoute
  '/actas/$actaId': typeof AuthenticatedActasActaIdRoute
  '/sistemas/$sistemaId': typeof AuthenticatedSistemasSistemaIdRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/actas/': typeof AuthenticatedActasIndexRoute
  '/areas/': typeof AuthenticatedAreasIndexRoute
  '/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/sistemas/': typeof AuthenticatedSistemasIndexRoute
  '/tickets/': typeof AuthenticatedTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRoute
  '/actas/$actaId': typeof AuthenticatedActasActaIdRoute
  '/sistemas/$sistemaId': typeof AuthenticatedSistemasSistemaIdRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/actas': typeof AuthenticatedActasIndexRoute
  '/areas': typeof AuthenticatedAreasIndexRoute
  '/permissions': typeof AuthenticatedPermissionsIndexRoute
  '/sistemas': typeof AuthenticatedSistemasIndexRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/actas/$actaId': typeof AuthenticatedActasActaIdRoute
  '/_authenticated/sistemas/$sistemaId': typeof AuthenticatedSistemasSistemaIdRoute
  '/_authenticated/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/_authenticated/actas/': typeof AuthenticatedActasIndexRoute
  '/_authenticated/areas/': typeof AuthenticatedAreasIndexRoute
  '/_authenticated/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/_authenticated/sistemas/': typeof AuthenticatedSistemasIndexRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/users'
    | '/actas/$actaId'
    | '/sistemas/$sistemaId'
    | '/tickets/$ticketId'
    | '/actas/'
    | '/areas/'
    | '/permissions/'
    | '/sistemas/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/users'
    | '/actas/$actaId'
    | '/sistemas/$sistemaId'
    | '/tickets/$ticketId'
    | '/actas'
    | '/areas'
    | '/permissions'
    | '/sistemas'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/users'
    | '/_authenticated/actas/$actaId'
    | '/_authenticated/sistemas/$sistemaId'
    | '/_authenticated/tickets/$ticketId'
    | '/_authenticated/actas/'
    | '/_authenticated/areas/'
    | '/_authenticated/permissions/'
    | '/_authenticated/sistemas/'
    | '/_authenticated/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actas/': {
      id: '/_authenticated/actas/'
      path: '/actas'
      fullPath: '/actas/'
      preLoaderRoute: typeof AuthenticatedActasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actas/$actaId': {
      id: '/_authenticated/actas/$actaId'
      path: '/actas/$actaId'
      fullPath: '/actas/$actaId'
      preLoaderRoute: typeof AuthenticatedActasActaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/areas/': {
      id: '/_authenticated/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AuthenticatedAreasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permissions/': {
      id: '/_authenticated/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AuthenticatedPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sistemas/': {
      id: '/_authenticated/sistemas/'
      path: '/sistemas'
      fullPath: '/sistemas/'
      preLoaderRoute: typeof AuthenticatedSistemasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sistemas/$sistemaId': {
      id: '/_authenticated/sistemas/$sistemaId'
      path: '/sistemas/$sistemaId'
      fullPath: '/sistemas/$sistemaId'
      preLoaderRoute: typeof AuthenticatedSistemasSistemaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/$ticketId': {
      id: '/_authenticated/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedActasActaIdRoute: typeof AuthenticatedActasActaIdRoute
  AuthenticatedSistemasSistemaIdRoute: typeof AuthenticatedSistemasSistemaIdRoute
  AuthenticatedTicketsTicketIdRoute: typeof AuthenticatedTicketsTicketIdRoute
  AuthenticatedActasIndexRoute: typeof AuthenticatedActasIndexRoute
  AuthenticatedAreasIndexRoute: typeof AuthenticatedAreasIndexRoute
  AuthenticatedPermissionsIndexRoute: typeof AuthenticatedPermissionsIndexRoute
  AuthenticatedSistemasIndexRoute: typeof AuthenticatedSistemasIndexRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedActasActaIdRoute: AuthenticatedActasActaIdRoute,
  AuthenticatedSistemasSistemaIdRoute: AuthenticatedSistemasSistemaIdRoute,
  AuthenticatedTicketsTicketIdRoute: AuthenticatedTicketsTicketIdRoute,
  AuthenticatedActasIndexRoute: AuthenticatedActasIndexRoute,
  AuthenticatedAreasIndexRoute: AuthenticatedAreasIndexRoute,
  AuthenticatedPermissionsIndexRoute: AuthenticatedPermissionsIndexRoute,
  AuthenticatedSistemasIndexRoute: AuthenticatedSistemasIndexRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
